### ISSUE TITLE
bug(develop_link): `development_setup` function fails

### ISSUE THREAD

**Issue by ryanfobel** [wheeler-microfluidics/conda-helpers#4]
# Steps to reproduce the error

## Method 1

1. Clone the latest ```base-node-rpc``` repository (currently v0.34):
```
git clone https://github.com/wheeler-microfluidics/base-node-rpc
```
2. Run the `paver develop_link` command:
```
cd base-node-rpc
paver develop_link
```
This results in the following error:

```python
CondaValueError: could not parse 'arduino-helpers 0.4 py27_0' in: c:\users\wheeler\appdata\local\temp\.conda-recipe-dev-req-iwxveq
ERROR:conda_helpers:Error executing command: `call C:\Users\Wheeler\MicroDrop\Scripts\activate.bat C:\Users\Wheeler\MicroDrop & conda install -y --file c:^\users^\wheeler^\appdata^\local^\temp^\.conda-recipe-dev-req-iwxveq`

Captured Task Output:
---------------------

---> base_node_rpc.pavement_base.develop_link
Traceback (most recent call last):
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\paver\tasks.py", line 196, in _run_task
    return do_task()
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\paver\tasks.py", line 193, in do_task
    return func(**kw)
  File ".\base_node_rpc\pavement_base.py", line 511, in develop_link
    package_name=options.package_name)
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\platformio_helpers\develop.py", line 60, in link
    ch.development_setup(recipe_dir, verbose=True)
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\conda_helpers\__init__.py", line 490, in development_setup
    conda_exec('install', '-y', '--file', development_reqs_file.name,
  File "C:\Users\Wheeler\MicroDrop\lib\site-packages\conda_helpers\__init__.py", line 366, in conda_exec
    raise RuntimeError(output)
RuntimeError:
CondaValueError: could not parse 'arduino-helpers 0.4 py27_0' in: c:\users\wheeler\appdata\local\temp\.conda-recipe-dev-req-iwxveq
```

## Method 2

A simpler way to reproduce the error is to run the following command with [this requirements file](https://github.com/wheeler-microfluidics/conda-helpers/files/1518051/development_reqs_file.txt)
):
```
conda install -y --file development_reqs_file.txt
```

It appears that the requirements file is not in the format that conda is expecting.

**Comment by cfobel** [comment]
I was able to run `paver develop_link` in sci-bots/base-node-rpc@4f2935a without issue using the following environment: [env-paver_develop_link-working-py27-x86.zip](https://github.com/sci-bots/conda-helpers/files/1601784/env-paver_develop_link-working-py27-x86.zip)

To set up the environment extract environment `.yaml` file and run:

    conda env create -n <env name> -f env-paver_develop_link-working-py27-x86.yaml

**Comment by ryanfobel** [comment]
Here's my environment that is not working: [env-paver_develop_link-not-working-py27-x86.zip](https://github.com/sci-bots/conda-helpers/files/1601835/env-paver_develop_link-not-working-py27-x86.zip)

It looks like the problem may be a result of a difference in the output of `conda render`. In my version, it produces dependencies with the format:

```
arduino-helpers 0.4 py27_0
```

**Comment by ryanfobel** [comment]
It turns out that this problem was caused by my environment having a different channel priority due to an additional conda config file in my User directory:

```
C:\Users\Wheeler>conda config --show-sources
==> C:\Users\Wheeler\MicroDrop\.condarc <==
channels:
  - sci-bots
  - microdrop-plugins
  - wheeler-microfluidics
  - conda-forge
  - defaults

==> C:\Users\Wheeler\.condarc <==
channels:
  - sci-bots
  - defaults
```

This forced installation of a newer version of the `conda-build` package (3.2.1 for the `default` channel vs 2.1.18 for `conda-forge`), which produces a different output from the `conda render` command. Removing this extra config file restored my channel priority and corrected the problem.

If/when `conda-forge` updates their version of `conda-build`, this problem is likely to return. In that case, potential solutions include:

1. Parsing the output of `conda render` to strip these additional fields.
2. Passing the package specs directly to `conda install` on the command line.
3. Writing the dependencies to a yaml file and use [`conda env update`](https://conda.io/docs/commands/env/conda-env-update.html).
  
Closing this issue for now.

**Comment by ryanfobel** [comment]
Here is a potential patch implementing option 2, but it probably isn't ideal since there are [limits](https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553) to the command line length on Windows.

```python
@@ -475,22 +475,12 @@ def development_setup(recipe_dir, *args, **kwargs):
     # they are not supported by `conda install`.
     development_reqs = filter(lambda v: '*' not in v, development_reqs)
 
-    # Dump list of Conda requirements to a file and install dependencies using
-    # `conda install ...`.
+    # Install dependencies using `conda install ...`.
     logger.info('Install build and run-time dependencies:\n%s',
                 '\n'.join(' {}'.format(r) for r in development_reqs))
-    development_reqs_file = tmp.TemporaryFile(mode='w', prefix='%s-dev-req-' %
-                                              recipe_dir.name, delete=False)
-    try:
-        # Create string containing one package descriptor per line.
-        development_reqs_str = '\n'.join(development_reqs)
-        development_reqs_file.file.write(development_reqs_str)
-        development_reqs_file.file.close()
-        conda_exec('install', '-y', '--file', development_reqs_file.name,
-                   *args, verbose=verbose)
-    finally:
-        # Remove temporary file containing list of Conda requirements.
-        ph.path(development_reqs_file.name).remove()
+
+    conda_exec('install', '-y', *(development_reqs + list(args)),
+               verbose=verbose)
 
 
 def install_info(install_response, split_version=False):
```

**Comment by ryanfobel** [comment]
`conda-forge` has now updated their `conda-build` package to version 3.4.1, so I am reopening this issue. As a workaround, you can force installation of version 2.1.18:

```
conda install conda-build=2.1.18
```

**Comment by cfobel** [comment]
As a temporary workaround, you can [pin the version][1] of Conda build:

```sh
conda config --add pinned_packages conda-build=2.1.18
```

[1]: https://github.com/conda/conda/issues/1718#issuecomment-300430334

**Comment by ryanfobel** [comment]
Yes thanks @cfobel, you have to downgrade the conda-build package and pin it; otherwise, running `paver develop_link` updates it again.
